-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 15:26:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Status_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status_client` (
  `ID_Status_client` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Status_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `ID_Client` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_contract` INT UNSIGNED NOT NULL,
  `FullName_client` VARCHAR(70) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Qualified_lead` VARCHAR(45) NOT NULL,
  `Status_client_ID_Status_client` INT NOT NULL,
  `LTV` INT NULL,
  PRIMARY KEY (`ID_Client`),
  INDEX `fk_Clients_Status_client1_idx` (`Status_client_ID_Status_client` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Status_client1`
    FOREIGN KEY (`Status_client_ID_Status_client`)
    REFERENCES `mydb`.`Status_client` (`ID_Status_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role_worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role_worker` (
  `ID_Role` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`worker` (
  `ID_worker` INT NOT NULL AUTO_INCREMENT,
  `ID_role` INT NULL,
  `ID_Clientsl` VARCHAR(45) NOT NULL,
  `FIO` VARCHAR(100) NULL,
  `Возраст` INT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `Role_worker_ID_Role` INT NOT NULL,
  PRIMARY KEY (`ID_worker`),
  UNIQUE INDEX `ID_worker_UNIQUE` (`ID_worker` ASC) VISIBLE,
  INDEX `fk_worker_Role_worker1_idx` (`Role_worker_ID_Role` ASC) VISIBLE,
  CONSTRAINT `fk_worker_Role_worker1`
    FOREIGN KEY (`Role_worker_ID_Role`)
    REFERENCES `mydb`.`Role_worker` (`ID_Role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`connection_contract_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`connection_contract_object` (
  `idconnection_contract_object` INT NOT NULL,
  PRIMARY KEY (`idconnection_contract_object`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `ID_Contract` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name_contract` VARCHAR(45) NOT NULL,
  `Cost` VARCHAR(45) NOT NULL,
  `date_signing` DATE NOT NULL,
  `Construction_Dates` INT NOT NULL,
  `END_DATE` DATE NOT NULL,
  `Clients_ID_Client` INT UNSIGNED NOT NULL,
  `worker_ID_worker` INT NOT NULL,
  `connection_contract_object_idconnection_contract_object` INT NOT NULL,
  PRIMARY KEY (`ID_Contract`),
  INDEX `fk_Contract_Clients1_idx` (`Clients_ID_Client` ASC) VISIBLE,
  INDEX `fk_Contract_worker1_idx` (`worker_ID_worker` ASC) VISIBLE,
  INDEX `fk_Contract_connection_contract_object1_idx` (`connection_contract_object_idconnection_contract_object` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Clients1`
    FOREIGN KEY (`Clients_ID_Client`)
    REFERENCES `mydb`.`Clients` (`ID_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_worker1`
    FOREIGN KEY (`worker_ID_worker`)
    REFERENCES `mydb`.`worker` (`ID_worker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_connection_contract_object1`
    FOREIGN KEY (`connection_contract_object_idconnection_contract_object`)
    REFERENCES `mydb`.`connection_contract_object` (`idconnection_contract_object`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`object` (
  `ID_object` INT NOT NULL AUTO_INCREMENT,
  `square` VARCHAR(45) NOT NULL,
  `cost` VARCHAR(45) NOT NULL,
  `building_dates` VARCHAR(45) NOT NULL,
  `number_floors` INT NOT NULL,
  `parking_space` VARCHAR(45) NOT NULL,
  `connection_contract_object_idconnection_contract_object` INT NOT NULL,
  PRIMARY KEY (`ID_object`),
  INDEX `fk_object_connection_contract_object1_idx` (`connection_contract_object_idconnection_contract_object` ASC) VISIBLE,
  CONSTRAINT `fk_object_connection_contract_object1`
    FOREIGN KEY (`connection_contract_object_idconnection_contract_object`)
    REFERENCES `mydb`.`connection_contract_object` (`idconnection_contract_object`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
